const Session = require("../Models/Session");
const Question = require("../Models/Question");

exports.createSession = async (req, res) => {
  try {
    const { 
      role, 
      experience, 
      topicsFocus, 
      description, 
      questions,
      interviewType = "general",
      company,
      jobRole,
      branch
    } = req.body;
    
    // FIX: Use _id (Mongoose document has _id, not id)
    const userId = req.user._id;

    console.log("📝 Creating session for user:", userId);

    // Validate required fields
    if (interviewType === "company" && (!company || !jobRole)) {
      return res.status(400).json({ 
        success: false, 
        message: "Company and jobRole are required for company interviews" 
      });
    }

    if (!role || !experience || !topicsFocus) {
      return res.status(400).json({ 
        success: false, 
        message: "Missing required fields: role, experience, topicsFocus" 
      });
    }

    // Handle questions
    let questionsArray = [];
    
    if (questions) {
      if (Array.isArray(questions)) {
        questionsArray = questions;
      } else if (typeof questions === 'object' && questions !== null) {
        if (questions.questions && Array.isArray(questions.questions)) {
          questionsArray = questions.questions;
        } else {
          questionsArray = Object.values(questions).filter(q => 
            q && typeof q === 'object' && q.question
          );
        }
      } else if (typeof questions === 'string') {
        try {
          const parsed = JSON.parse(questions);
          if (Array.isArray(parsed)) {
            questionsArray = parsed;
          } else if (parsed.questions && Array.isArray(parsed.questions)) {
            questionsArray = parsed.questions;
          }
        } catch (e) {
          console.log("Questions string not parseable:", e.message);
        }
      }
    }

    // Default questions if none provided
    if (questionsArray.length === 0) {
      questionsArray = [
        {
          question: `Tell me about your experience with ${topicsFocus || 'your tech stack'}.`,
          answer: "Expected answer would depend on candidate's experience",
          type: "general"
        },
        {
          question: "Describe a challenging project you worked on.",
          answer: "Use STAR method: Situation, Task, Action, Result",
          type: "behavioral"
        }
      ];
    }

    const sessionData = {
      user: userId, // Use _id
      role,
      experience: parseInt(experience),
      topicsFocus,
      description: description || "",
      questions: [],
      interviewType,
      branch: branch || "General"
    };

    if (interviewType === "company") {
      sessionData.company = company;
      sessionData.jobRole = jobRole;
    }

    // Create session
    const session = await Session.create(sessionData);
    console.log("✅ Session created with ID:", session._id);

    // Create questions
    const questionDocs = [];
    
    for (let i = 0; i < questionsArray.length; i++) {
      const q = questionsArray[i];
      try {
        const questionText = q.question || q.text || q.content || `Question ${i + 1}`;
        const answerText = q.answer || q.expectedAnswer || q.solution || 
          (q.detailedAnswer ? q.detailedAnswer : (q.shortAnswer ? q.shortAnswer : ""));
        const questionType = q.type || q.category || 
          (questionText.toLowerCase().includes('tell me about') ? 'behavioral' : 'technical');

        const question = await Question.create({
          session: session._id,
          question: questionText,
          answer: answerText || "Answer will be generated by AI",
          type: questionType,
          difficulty: q.difficulty || "medium",
          isPinned: false
        });
        
        questionDocs.push(question._id);
        console.log(`✅ Created question ${i + 1}`);
      } catch (qError) {
        console.error(`❌ Error creating question ${i}:`, qError.message);
      }
    }

    // Update session with questions
    session.questions = questionDocs;
    await session.save();

    // Populate and return
    const populatedSession = await Session.findById(session._id)
      .populate("questions")
      .lean();

    res.status(201).json({ 
      success: true, 
      session: populatedSession
    });
  } catch (error) {
    console.error("❌ Error creating session:", error);
    res.status(500).json({ 
      success: false, 
      message: "Server Error",
      error: error.message 
    });
  }
};

// FIXED: Get My Sessions
exports.getMySession = async (req, res) => {
  try {
    // Use _id from Mongoose document
    const userId = req.user._id;
    
    console.log("📊 Fetching sessions for user:", userId);
    
    const sessions = await Session.find({ user: userId })
      .sort({ createdAt: -1 })
      .populate("questions")
      .lean();

    console.log(`✅ Found ${sessions?.length || 0} sessions`);

    res.status(200).json({ 
      success: true, 
      sessions: sessions || [],
      count: sessions?.length || 0 
    });
  } catch(err) {
    console.error("❌ Error in getMySession:", err);
    res.status(500).json({ 
      success: false,
      message: "Server Error",
      error: err.message 
    });
  }
};

// FIXED: Get Session By ID
exports.getSessionById = async (req, res) => {
  try {
    const userId = req.user._id;
    
    const session = await Session.findById(req.params.id)
      .populate({
        path: "questions",
        options: { sort: { isPinned: -1, createdAt: 1 } },
      })
      .lean();
    
    if (!session) {
      return res.status(404).json({ 
        success: false, 
        message: "Session not found"
      });
    }

    // Convert ObjectId to string for comparison
    if (session.user.toString() !== userId.toString()) {
      return res.status(403).json({ 
        success: false, 
        message: "Not authorized to access this session" 
      });
    }

    res.status(200).json({ 
      success: true, 
      session 
    });
  } catch(err) {
    console.error("❌ Error in getSessionById:", err);
    res.status(500).json({ 
      success: false,
      message: "Server Error",
      error: err.message 
    });
  }
};

// FIXED: Delete Session
exports.deleteSession = async (req, res) => {
  try {
    const userId = req.user._id;
    
    const session = await Session.findById(req.params.id);

    if (!session) {
      return res.status(404).json({ 
        success: false, 
        message: "Session not found" 
      });
    }

    if (session.user.toString() !== userId.toString()) {
      return res.status(403).json({ 
        success: false, 
        message: "Not authorized to delete this session" 
      });
    }

    await Question.deleteMany({ session: session._id });
    await Session.findByIdAndDelete(req.params.id);

    res.status(200).json({ 
      success: true, 
      message: "Session successfully deleted" 
    });
  } catch(err) {
    console.error("❌ Error in deleteSession:", err);
    res.status(500).json({ 
      success: false,
      message: "Server Error",
      error: err.message 
    });
  }
};

// FIXED: Get Sessions By Type
exports.getSessionsByType = async (req, res) => {
  try {
    const { type } = req.params;
    const userId = req.user._id;
    
    const sessions = await Session.find({ 
      user: userId,
      interviewType: type 
    })
      .sort({ createdAt: -1 })
      .populate("questions")
      .lean();

    res.status(200).json({ 
      success: true, 
      sessions: sessions || [],
      count: sessions?.length || 0 
    });
  } catch(err) {
    console.error("❌ Error in getSessionsByType:", err);
    res.status(500).json({ 
      success: false,
      message: "Server Error",
      error: err.message 
    });
  }
};

// FIXED: Toggle Pin Question
exports.togglePinQuestion = async (req, res) => {
  try {
    const { questionId } = req.params;
    const userId = req.user._id;
    
    const question = await Question.findById(questionId);
    
    if (!question) {
      return res.status(404).json({ 
        success: false, 
        message: "Question not found" 
      });
    }

    const session = await Session.findById(question.session);
    if (!session || session.user.toString() !== userId.toString()) {
      return res.status(403).json({ 
        success: false, 
        message: "Not authorized" 
      });
    }

    question.isPinned = !question.isPinned;
    await question.save();

    res.status(200).json({ 
      success: true, 
      isPinned: question.isPinned,
      message: question.isPinned ? "Question pinned" : "Question unpinned"
    });
  } catch(err) {
    console.error("❌ Error toggling pin:", err);
    res.status(500).json({ 
      success: false,
      message: "Server Error",
      error: err.message 
    });
  }
};

// FIXED: Update Question Answer
exports.updateQuestionAnswer = async (req, res) => {
  try {
    const { questionId } = req.params;
    const { answer } = req.body;
    const userId = req.user._id;
    
    const question = await Question.findById(questionId);
    
    if (!question) {
      return res.status(404).json({ 
        success: false, 
        message: "Question not found" 
      });
    }

    const session = await Session.findById(question.session);
    if (!session || session.user.toString() !== userId.toString()) {
      return res.status(403).json({ 
        success: false, 
        message: "Not authorized" 
      });
    }

    question.answer = answer;
    await question.save();

    res.status(200).json({ 
      success: true, 
      question 
    });
  } catch(err) {
    console.error("❌ Error updating answer:", err);
    res.status(500).json({ 
      success: false,
      message: "Server Error",
      error: err.message 
    });
  }
};