export const COMPANY_NAME = [
  "Google",
  "Microsoft",
  "Amazon",
  "Facebook",
  "Apple",
  "Netflix",
  "Tesla",
  "Adobe",
  "IBM",
  "Intel",
  "Oracle",
  "Salesforce",
  "Uber",
  "Airbnb",
  "Twitter",
  "LinkedIn",
  // Indian companies
  "Tata Consultancy Services (TCS)",
  "Infosys",
  "Wipro",
  "HCL Technologies",
  "Tech Mahindra",
  "Larsen & Toubro Infotech (LTI)",
  "Mindtree",
  "Cognizant",
  "Capgemini India",
  "Accenture India",
  "Flipkart",
  "Paytm",
  "Freshworks",
  "Reliance Jio",
  "Other",
];

export const COMPANY_JOB_ROLE = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Mobile App Developer",
  "QA Engineer",
  "Product Manager",
  "Business Analyst",
  "UI/UX Designer",
  "System Administrator",
  "Network Engineer",
  "Database Administrator",
  "Technical Support Engineer",
  "Site Reliability Engineer",
  "Security Analyst",
  "AI Engineer",
  "Other",
];